[2024-07-09T01:24:19.630+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T01:24:19.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline.Load scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T01:24:19.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline.Load scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T01:24:19.671+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-09T01:24:19.690+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): Load> on 2024-07-08 00:00:00+00:00
[2024-07-09T01:24:19.702+0000] {standard_task_runner.py:63} INFO - Started process 3493 to run task
[2024-07-09T01:24:19.704+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_pipeline', 'Load', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpptf21uq8']
[2024-07-09T01:24:19.706+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask Load
[2024-07-09T01:24:19.769+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline.Load scheduled__2024-07-08T00:00:00+00:00 [running]> on host 338dcb453384
[2024-07-09T01:24:19.958+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_pipeline' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T00:00:00+00:00'
[2024-07-09T01:24:19.960+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T01:24:19.963+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-07-09T01:24:19.964+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-09T01:24:19.965+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T01:24:19.974+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_pipeline, task_id=Load, run_id=scheduled__2024-07-08T00:00:00+00:00, execution_date=20240708T000000, start_date=20240709T012419, end_date=20240709T012419
[2024-07-09T01:24:20.038+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-09T01:24:20.058+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T01:24:20.061+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-09T01:37:00.602+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T01:37:00.723+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline.Load scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T01:37:00.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline.Load scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-07-09T01:37:00.743+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-09T01:37:00.767+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): Load> on 2024-07-08 00:00:00+00:00
[2024-07-09T01:37:00.785+0000] {standard_task_runner.py:63} INFO - Started process 180 to run task
[2024-07-09T01:37:00.789+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_pipeline', 'Load', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpd6ih3put']
[2024-07-09T01:37:00.791+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask Load
[2024-07-09T01:37:00.995+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline.Load scheduled__2024-07-08T00:00:00+00:00 [running]> on host 2a22a675a9f6
[2024-07-09T01:37:01.550+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_pipeline' AIRFLOW_CTX_TASK_ID='Load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-08T00:00:00+00:00'
[2024-07-09T01:37:01.553+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T01:37:01.558+0000] {logging_mixin.py:188} INFO - An error occurred: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-07-09T01:37:01.559+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-09T01:37:01.560+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T01:37:01.623+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_pipeline, task_id=Load, run_id=scheduled__2024-07-08T00:00:00+00:00, execution_date=20240708T000000, start_date=20240709T013700, end_date=20240709T013701
[2024-07-09T01:37:01.685+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-09T01:37:01.769+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T01:37:01.773+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
